version: "3.9"

services:
  app:
    build: .
    security_opt:
      - apparmor=unconfined
    working_dir: /app
    command: python -m uvicorn app.app:app --host 0.0.0.0 --port 8000 --loop asyncio
    environment:
#      DATABASE_URL: sqlite+aiosqlite:///./archaeological_catalog.db
      DATABASE_URL: sqlite+aiosqlite:////app/data/archaeological_catalog.db
      MINIO_CONFIG_PROFILE: local
      MINIO_LOCAL_URL: http://minio:9000
      MINIO_LOCAL_ACCESS_KEY: minioadmin
      MINIO_LOCAL_SECRET_KEY: minioadmin
      MINIO_LOCAL_BUCKET: archaeological-photos
      MINIO_LOCAL_SECURE: "false"
      CSRF_SECRET_KEY: "cambia-con-una-stringa-segreta-lunga"
      COOKIE_SAMESITE: "lax"
      COOKIE_SECURE: "false"
    ports:
      - "8000:8000"
    depends_on:
      - minio
    volumes:
      - .:/app
      - ./data:/app/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
