# app/models/harris_matrix_mapping.py
"""
Model for persistent storage of temporary-to-database ID mappings in Harris Matrix system.
Provides audit trail and session-based organization for multi-user support.
"""

import uuid
from datetime import datetime
from enum import Enum as PyEnum
from typing import Optional, Dict, Any

from sqlalchemy import Column, String, DateTime, Index, UniqueConstraint, Integer
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from app.models.base import Base


class MappingStatusEnum(str, PyEnum):
    """Status of mapping entries"""
    ACTIVE = "active"      # Currently active mapping
    COMMITTED = "committed"  # Successfully committed transaction
    ROLLBACK = "rollback"   # Rolled back transaction
    EXPIRED = "expired"     # Expired session mapping


class HarrisMatrixMapping(Base):
    """Persistent storage for temporary-to-database ID mappings.
    
    This model maintains the relationship between temporary IDs generated
    by the frontend and actual database IDs, enabling recovery scenarios
    and supporting multi-user concurrent editing sessions.
    """
    __tablename__ = "harris_matrix_mappings"

    # === PRIMARY KEY ===
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # === RELATIONSHIP FIELDS ===
    site_id = Column(UUID(as_uuid=True), nullable=False, index=True, 
                     comment="Site identifier for multi-tenant isolation")
    session_id = Column(String(255), nullable=False, index=True,
                       comment="User session identifier for multi-user support")
    temp_id = Column(String(255), nullable=False,
                    comment="Temporary ID generated by frontend")
    db_id = Column(UUID(as_uuid=True), nullable=False, index=True,
                  comment="Actual database UUID identifier")
    unit_code = Column(String(50), nullable=False, index=True,
                      comment="Human-readable unit code (e.g., 'US003')")

    # === AUDIT FIELDS ===
    transaction_id = Column(String(255), nullable=True, index=True,
                           comment="Transaction identifier for audit trail")
    created_at = Column(DateTime, server_default=func.now(), nullable=False,
                       comment="Timestamp when mapping was created")
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False,
                       comment="Timestamp when mapping was last updated")
    status = Column(String(20), default=MappingStatusEnum.ACTIVE, nullable=False, index=True,
                   comment="Current status of the mapping")

    # === METADATA FIELDS ===
    user_id = Column(UUID(as_uuid=True), nullable=True, index=True,
                    comment="User who created the mapping")
    expires_at = Column(DateTime, nullable=True, index=True,
                       comment="Expiration timestamp for automatic cleanup")
    retry_count = Column(Integer, default=0, nullable=False,
                        comment="Number of retry attempts for this mapping")
    last_accessed = Column(DateTime, nullable=True,
                          comment="Last time this mapping was accessed")

    # === TABLE CONSTRAINTS ===
    __table_args__ = (
        # Prevent duplicate temporary IDs within the same site
        UniqueConstraint('site_id', 'temp_id', name='unique_site_temp_id'),
        # Index for efficient session-based queries
        Index('idx_site_session', 'site_id', 'session_id'),
        # Index for transaction-based operations
        Index('idx_transaction', 'transaction_id', 'status'),
        # Composite index for status-based cleanup queries
        Index('idx_status_expires', 'status', 'expires_at'),
        # Index for unit code lookups
        Index('idx_site_unit_code', 'site_id', 'unit_code'),
    )

    def __repr__(self):
        return f"<HarrisMatrixMapping(site_id={self.site_id}, temp_id={self.temp_id}, db_id={self.db_id}, status={self.status})>"

    def __str__(self):
        return f"{self.unit_code} ({self.temp_id} → {self.db_id})"

    # === PROPERTIES ===

    @property
    def is_active(self) -> bool:
        """Check if mapping is currently active"""
        return self.status == MappingStatusEnum.ACTIVE

    @property
    def is_expired(self) -> bool:
        """Check if mapping has expired"""
        if not self.expires_at:
            return False
        return datetime.utcnow() > self.expires_at

    @property
    def is_committed(self) -> bool:
        """Check if mapping was successfully committed"""
        return self.status == MappingStatusEnum.COMMITTED

    @property
    def is_rollback(self) -> bool:
        """Check if mapping was rolled back"""
        return self.status == MappingStatusEnum.ROLLBACK

    # === METHODS ===

    def commit(self, transaction_id: Optional[str] = None):
        """Mark mapping as committed"""
        self.status = MappingStatusEnum.COMMITTED
        if transaction_id:
            self.transaction_id = transaction_id
        self.updated_at = datetime.utcnow()

    def rollback(self, transaction_id: Optional[str] = None):
        """Mark mapping as rolled back"""
        self.status = MappingStatusEnum.ROLLBACK
        if transaction_id:
            self.transaction_id = transaction_id
        self.updated_at = datetime.utcnow()

    def expire(self):
        """Mark mapping as expired"""
        self.status = MappingStatusEnum.EXPIRED
        self.updated_at = datetime.utcnow()

    def touch(self):
        """Update last accessed timestamp"""
        self.last_accessed = datetime.utcnow()
        self.updated_at = datetime.utcnow()

    def increment_retry(self):
        """Increment retry count"""
        self.retry_count += 1
        self.updated_at = datetime.utcnow()
        self.touch()

    def set_expiration(self, hours: int = 24):
        """Set expiration timestamp"""
        from datetime import timedelta
        self.expires_at = datetime.utcnow() + timedelta(hours=hours)
        self.updated_at = datetime.utcnow()

    # === SERIALIZATION ===

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for API responses"""
        return {
            'id': str(self.id),
            'site_id': str(self.site_id),
            'session_id': self.session_id,
            'temp_id': self.temp_id,
            'db_id': str(self.db_id),
            'unit_code': self.unit_code,
            'transaction_id': self.transaction_id,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
            'expires_at': self.expires_at.isoformat() if self.expires_at else None,
            'user_id': str(self.user_id) if self.user_id else None,
            'retry_count': self.retry_count,
            'last_accessed': self.last_accessed.isoformat() if self.last_accessed else None,
        }

    def to_compact_dict(self) -> Dict[str, Any]:
        """Compact version for mapping responses"""
        return {
            'temp_id': self.temp_id,
            'db_id': str(self.db_id),
            'unit_code': self.unit_code,
            'status': self.status,
        }

    # === CLASS METHODS ===

    @classmethod
    def create_mapping(cls, site_id: uuid.UUID, session_id: str, temp_id: str,
                      db_id: uuid.UUID, unit_code: str, user_id: Optional[uuid.UUID] = None,
                      transaction_id: Optional[str] = None, expires_hours: int = 24) -> 'HarrisMatrixMapping':
        """Create a new mapping instance"""
        mapping = cls(
            site_id=site_id,
            session_id=session_id,
            temp_id=temp_id,
            db_id=db_id,
            unit_code=unit_code,
            user_id=user_id,
            transaction_id=transaction_id
        )
        
        if expires_hours > 0:
            mapping.set_expiration(expires_hours)
            
        return mapping

    @classmethod
    def get_status_choices(cls) -> list:
        """Get list of valid status choices"""
        return [
            {'value': status.value, 'label': status.value.title()}
            for status in MappingStatusEnum
        ]